---
name: colortransfer
version: 1.0.0.0
license: MIT
license-file: LICENSE
dependencies:
  - base
  - bytestring
  - hmatrix
  - JuicyPixels
  - optparse-generic
  - relude
ghc-options:
  - -fwrite-ide-info
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -Wcpp-undef
  - -Wunused-packages

extra-source-files:
  - ./test-resources/originals/*.jpg
  - ./test-resources/processed/*.jpeg

library:
  source-dirs: ./src/

executables:
  colortransfer:
    main: Main.hs
    source-dirs: ./src/
    ghc-options: 
      - -rtsopts
      - -threaded
      - -O2 -optc-O3 -optc-ffast-math
      - -fexcess-precision 
      - -with-rtsopts=-N
tests:
  colortransfer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -O2 -optc-O3 -optc-ffast-math
      - -fexcess-precision 
    dependencies:
      - QuickCheck
      - sydtest
      - sydtest-discover
      - colortransfer
      - filepath
