---
name: colortransfer
version: 1.0.0.0
license: MIT
license-file: LICENSE
dependencies:
  - base
  - bytestring
  - hmatrix
  - JuicyPixels
  - optparse-generic
  - relude
ghc-options:
  - -fwrite-ide-info
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -Wcpp-undef
  - -Wunused-packages

library:
  source-dirs: ./src/
executables:
  colortransfer:
    main: Main.hs
    source-dirs: ./src/
    ghc-options: [-Wall, -rtsopts, -threaded, -with-rtsopts=-N, -O2]
