---
name: colortransfer
version: 0.1.0.0
license: MIT
license-file: LICENSE
dependencies:
  - base
  - bytestring
  - optparse-applicative
  - optparse-generic
  - relude
  - text
  - JuicyPixels
library:
  source-dirs: ./src/
executables:
  colortransfer:
    main: Main.hs
    source-dirs: ./src/
    ghc-options: [-rtsopts, -threaded, -with-rtsopts=-N, -O2]
