---
name: colortransfer
version: 1.0.0.0
license: MIT
license-file: LICENSE
dependencies:
  - base
  - bytestring
  - optparse-generic
  - JuicyPixels
  - free
  - comonad
  - generic-lens
  - lens
  - text
  - mtl
  - fixplate
library:
  source-dirs: ./src/
executables:
  colortransfer:
    main: Main.hs
    source-dirs: ./src/
    ghc-options: [-Wall, -rtsopts, -threaded, -with-rtsopts=-N, -O2]
