name: build-project
on: push
#
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install nix
        uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: opensource
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: damianfral/nix-cache-lookup@master
        id: cache-lookup-default
        name: Check if already cached
        with:
          flake-attribute: .#default
      - run: nix build --accept-flake-config

        if: steps.cache-lookup-default.outputs.cached != 'true'
  build-dev-shell:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install nix
        uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: opensource
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: damianfral/nix-cache-lookup@master
        id: cache-lookup-dev-shell-default
        name: Check if already cached
        with:
          flake-attribute: .#devShells.x86_64-linux.default
      - run: nix build .#devShells.x86_64-linux.default --accept-flake-config
        if: steps.cache-lookup-dev-shell-default.outputs.cached != 'true'
